# Play with DL

### First, let's go through the tutorials from TensorFlow

Setup tensorflow

In [59]:
import os
import numpy as np
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf

In [60]:
print('TensorFlow version: ', tf.__version__)
np.__version__

TensorFlow version:  2.11.0


'1.24.0'

What running device?

In [61]:
print("GPUs Available: ", tf.config.list_physical_devices('GPU'))

GPUs Available:  [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


What's next? At first try mnist

In [62]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_test, x_train = x_test / 255.0, x_train / 255.0

Create model

In [63]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

Test prediction

In [64]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.3780721 ,  0.02903594,  0.11067948,  0.6509585 ,  0.10889394,
        -0.2517399 ,  0.32370362, -0.1498838 ,  0.13592972, -0.11634855]],
      dtype=float32)

Make probabilities from this output

In [65]:
tf.nn.softmax(predictions).numpy()

array([[0.12479798, 0.08802844, 0.09551693, 0.16395345, 0.09534653,
        0.06647887, 0.11819404, 0.07360701, 0.09795947, 0.07611729]],
      dtype=float32)

Define a loos functon for train

In [66]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

Loss is zero if model confident of the correct class

Model not trained, so the probs will be random (something like 1/10 for each class), then loss will be closer to `log(1/10) ~= 2.3`
Let's watch)

In [67]:
loss_fn(y_train[:1], predictions).numpy()

2.7108712

Compile model

In [68]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train model!)
Start training with 5 epochs

In [71]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2993 - accuracy: 0.9121
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1439 - accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1076 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0866 - accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0732 - accuracy: 0.9776


Fine! Let's try more epochs, for example 15

In [37]:
model.fit(x_train, y_train, epochs=15)

Epoch 1/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0654 - accuracy: 0.9794
Epoch 2/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0578 - accuracy: 0.9812
Epoch 3/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0512 - accuracy: 0.9833
Epoch 4/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0455 - accuracy: 0.9849
Epoch 5/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0443 - accuracy: 0.9852
Epoch 6/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0415 - accuracy: 0.9861
Epoch 7/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0368 - accuracy: 0.9871
Epoch 8/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0356 - accuracy: 0.9877
Epoch 9/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0348 - accuracy: 0.9882
Epoch 10/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.030

I want to overfit this model, interesting how more epochs need?

In [70]:
history = model.fit(x_train, y_train, epochs=30, validation_data=(x_test, y_test))

AttributeError: 'Sequential' object has no attribute 'fitz'

Mnist is small dataset, and classes have not many features, but anyway we can see overfitting. Real accuracy decreases with increasing epochs after some point(E 20)

Get accuracy with other method

In [72]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0713 - accuracy: 0.9775 - 850ms/epoch - 3ms/step


[0.07132787257432938, 0.9775000214576721]

Look at the learning history

In [56]:
from matplotlib import pyplot as plt

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model fitting history')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='upper left')
plt.show()

NameError: name 'history' is not defined

In [51]:
history_long = model.fit(x_train, y_train, epochs=200, validation_data=(x_test, y_test))

Epoch 1/100
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0097 - accuracy: 0.9975 - val_loss: 0.2160 - val_accuracy: 0.9797
Epoch 2/100
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0087 - accuracy: 0.9976 - val_loss: 0.2088 - val_accuracy: 0.9819
Epoch 3/100
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0084 - accuracy: 0.9978 - val_loss: 0.2099 - val_accuracy: 0.9809
Epoch 4/100
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0081 - accuracy: 0.9977 - val_loss: 0.2131 - val_accuracy: 0.9807
Epoch 5/100
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0080 - accuracy: 0.9977 - val_loss: 0.2201 - val_accuracy: 0.9801
Epoch 6/100
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0091 - accuracy: 0.9976 - val_loss: 0.2124 - val_accuracy: 0.9794
Epoch 7/100
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0091 - accuracy: 0.9974 - val_loss: 0.2280 - val_ac

In [55]:
plt.plot(history_long.history['accuracy'])
plt.plot(history_long.history['val_accuracy'])
plt.title('model fitting history')
plt.xlabel('epoch')
plt.legend(['train', 'validation'], loc='upper left')
plt.show()

NameError: name 'plt' is not defined

Now I wat get probs on output

In [35]:
model.add(tf.keras.layers.Softmax())

Retrain model!

In [74]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

Get this probs

In [75]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.6972550e-08, 2.1117310e-09, 5.8769058e-07, 2.4877840e-05,
        1.5265258e-11, 1.1009867e-07, 1.3490379e-13, 9.9997306e-01,
        6.7478695e-08, 1.2328732e-06],
       [1.1889922e-08, 2.3476594e-05, 9.9996865e-01, 3.4251193e-06,
        7.0457598e-15, 3.9831170e-06, 3.0361733e-09, 2.3619458e-13,
        4.9525642e-07, 4.1032509e-13],
       [5.0189342e-08, 9.9822158e-01, 2.0852653e-04, 8.2233664e-06,
        2.9281667e-04, 6.5046945e-05, 1.9719459e-05, 9.1856916e-04,
        2.6252796e-04, 3.1246452e-06],
       [9.9994838e-01, 1.3613373e-08, 4.1711286e-05, 7.6391490e-07,
        5.3331331e-07, 4.4147901e-06, 1.9001253e-06, 1.8943281e-06,
        3.5485181e-09, 5.0340770e-07],
       [6.7779604e-07, 5.9928222e-09, 6.5102963e-06, 3.1048653e-08,
        9.9832839e-01, 5.1365572e-07, 2.1845647e-06, 2.5253055e-05,
        1.3138197e-07, 1.6362818e-03]], dtype=float32)>